# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef1aa1b325a00bd4ece48dd89c8e2b831a52de6dad18aed1f56dea98c9dfc09510f58a84211d5558998fcde89a45c851ac2de31a353b72742445ac03a8f6d495

test:
  secret_key_base: a8033e02fc2212cab0cf502ac75f414d0d859b54834678bff3ab463eaf352d0cb2852da205135c046302daf26116d582c8dbe2c32b2d940a8e8540b3fb708f2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
